const products = [
  {
    id: 1,
    type: "T-shirt",
    gender: "men",
    price: 250,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 2,
    type: "Jeans",
    gender: "women",
    price: 220,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 3,
    type: "Sweater",
    gender: "men",
    price: 270,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 4,
    type: "Jeans",
    gender: "women",
    price: 230,
    status: "Out of stock",
    imgUrl: "some_URL",
  },
  {
    id: 5,
    type: "T-shirt",
    gender: "men",
    price: 800,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 6,
    type: "Jacket",
    gender: "women",
    price: 700,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 7,
    type: "T-shirt",
    gender: "men",
    price: 900,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 8,
    type: "Jeans",
    gender: "women",
    price: 750,
    status: "Out of stock",
    imgUrl: "some_URL",
  },
  {
    id: 9,
    type: "Jacket",
    gender: "men",
    price: 400,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 10,
    type: "T-shirt",
    gender: "women",
    price: 350,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 11,
    type: "Sweater",
    gender: "men",
    price: 420,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 12,
    type: "Jacket",
    gender: "women",
    price: 370,
    status: "Out of stock",
    imgUrl: "some_URL",
  },
  {
    id: 13,
    type: "Jeans",
    gender: "men",
    price: 180,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 14,
    type: "Sweater",
    gender: "women",
    price: 160,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 15,
    type: "Jacket",
    gender: "men",
    price: 200,
    status: "In stock",
    imgUrl: "some_URL",
  },
  {
    id: 16,
    type: "Sweater",
    gender: "women",
    price: 170,
    status: "Out of stock",
    imgUrl: "some_URL",
  },
];
